export enum NOTIFICATION_CATEGORY {
  ALL, FOLLOWING, ARCHIVE, PINNED
}

export enum NOTIFICATION_ITEM_TYPE {
  GROUP_INVITE, GROUP_ACCEPT, GROUP_REJECT, GROUP_UPDATE,
  FRIEND_REQUEST, FRIEND_ACCEPT,
  ANNOUNCEMENT
}

export enum INBOX_CATEGORY {
  FOLLOWING, NOTICE
}